name: announcement
description: Announcement

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # icons
  cupertino_icons: ^1.0.2

  # state management
  flutter_bloc: ^8.1.3

  # service locator
  get_it: ^7.6.0

  # class generator
  freezed_annotation: ^2.4.1

  # firebase
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  firebase_database: ^10.2.4
  firebase_storage: ^11.2.5
  firebase_crashlytics: ^3.3.4
  firebase_messaging: ^14.6.6
  firebase_analytics: ^10.4.4

  image_picker: ^1.0.2

  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: ^4.2.1

  cached_network_image: ^3.2.3

  intl: ^0.18.1

  json_annotation: ^4.8.1

  device_info_plus: ^9.0.3

  flutter_local_notifications: ^15.1.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # manage role
  flutter_lints: ^2.0.0

  # code generator
  build_runner: ^2.4.6

  # class generator
  freezed: ^2.4.2
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true